✨ End to end tests
ionos-cloud/cluster-api-provider-ionoscloud pull request #137
Opened 2024-05-28 07:51 UTC by gfariasalves-ionos

**What is the purpose of this pull request/Why do we need it?**

Our changes aren't safe until we run end-to-end tests. We also want our provider to be conformant, so we need to check that.

**Description of changes:**

- E2E (conformance and non-conformance) tests are added.
- GitHub workflows for the tests are added.

**Special notes for your reviewer:**

- Failure in conformance is out of scope for the ticket. As long as the tests are running correctly, it is okay.
- [Developing E2E Tests](https://cluster-api.sigs.k8s.io/developer/e2e) and [Cluster API test directory](https://github.com/kubernetes-sigs/cluster-api/tree/main/test) are what I based myself on. Might be useful for knowing what to review!

**Checklist:**
- [x] Documentation updated
- [ ] Unit Tests added
- [x] E2E Tests added
- [x] Includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)

2024-06-04 12:47 UTC, jriedel-ionos requested changes

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/config/ionoscloud.yaml
Is it intended that `v1.7` is hardcoded everywhere?

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/data/infrastructure-ionoscloud/cluster-template.yaml
> +          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
You could either copy this from https://github.com/ionos-cloud/cluster-api-provider-ionoscloud/pull/140, or just remove the Diffie-Hellman stuff

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/data/infrastructure-ionoscloud/cluster-template.yaml
> +            KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
same as above ^

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/suite_test.go
> +	flag.StringVar(&artifactFolder, "e2e.artifacts-folder", "/home/gustavo/GolandProjects/cluster-api-provider-ionoscloud/_artifacts", "folder where e2e test artifact should be stored")
Fix your debugging paths :)

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/suite_test.go
> +	//createCredentialsSecret()
I guess this is not needed?

2024-06-04 12:47 UTC, jriedel-ionos commented on test/e2e/suite_test.go
> +//func createCredentialsSecret() {
Can maybe also be removed?

2024-06-04 15:49 UTC, jriedel-ionos commented on hack/scripts/remove-sensitive-data-from-artifacts.sh
Yeah you're right, was just out of intuition

2024-06-05 17:34 UTC, avorima commented on test/e2e/env_test.go
> +	Expect(ignoreNotFound(err)).To(Succeed(), "could not get credentials secret")
use controller-runtime's `client.IgnoreNotFound`

2024-06-06 09:32 UTC, mcbenjemaa requested changes

2024-06-06 09:32 UTC, mcbenjemaa commented on test/e2e/config/ionoscloud.yaml
> +  default/wait-control-plane: [ "20m", "10s" ]
You need to take into consideration the slowness of API or provisioning.

2024-06-06 09:32 UTC, mcbenjemaa commented on .github/workflows/e2e.yaml
> +    - name: Install kubectl and kustomize
There is no need for this step,

kubectl and kustomize should be available by builtin runners

2024-06-06 09:32 UTC, mcbenjemaa commented on .github/workflows/e2e.yaml
> +    - name: Build image
I prefer if you make the build image part of the test-e2e target in make file, as a dependency

2024-06-06 09:32 UTC, mcbenjemaa commented on .github/workflows/e2e.yaml
> +      run: make GINKGO_LABEL="!Conformance" test-e2e
Please put the Label by default in the Makefile

2024-06-06 09:40 UTC, mcbenjemaa reviewed
3 test cases is a bit too much,

I suggest having 2 cases:

* Single node cluster and then scaling workers
* Highly available Cluster with 3 cp and 3 workers.

2024-06-06 09:48 UTC, mcbenjemaa commented on .github/workflows/e2e.yaml
> +  pull_request:
How about the PR coming from forks
are we going to include them in e2e?

2024-06-06 09:48 UTC, mcbenjemaa commented on .github/workflows/e2e.yaml
> +  pull_request:
/cc @avorima

2024-06-06 14:19 UTC, mcbenjemaa commented on test/e2e/config/ionoscloud.yaml
> +  KUBERNETES_VERSION_MANAGEMENT: "v1.29.2"
but the 2 are the same version

2024-06-06 16:39 UTC, avorima commented on .github/workflows/e2e.yaml
> +concurrency:
We only added this in our repos, because they were triggered by every push. With the added safety of deployments it's no longer necessary

2024-06-11 18:34 UTC, mcbenjemaa commented on test/e2e/md_scale_test.go
> +var _ = Describe("When testing MachineDeployment scale out/in", func() {
```suggestion
var _ = Describe("Should create a cluster with 1 worker node and can be scaled", func() {
```

2024-06-11 18:34 UTC, mcbenjemaa commented on test/e2e/quickstart_test.go
> +var _ = Describe("When following the Cluster API quick-start (high availability)", func() {
```suggestion
var _ = Describe("Should create a cluster with 3 control-plane and 2 worker nodes", func() {
```

2024-06-11 18:34 UTC, mcbenjemaa commented on test/e2e/quickstart_test.go
> +var _ = Describe("When following the Cluster API quick-start (high availability)", func() {
I prefer placing all tests in a file `capic_test.go`

2024-06-12 15:06 UTC, merged