✨ Handle IP blocks based on VDC location
ionos-cloud/cluster-api-provider-ionoscloud pull request #172
Opened 2024-07-09 11:29 UTC by jriedel-ionos

**What is the purpose of this pull request/Why do we need it?**
If you specify a different VDC ID in the IonosCloudMachine spec, IP blocks are now correctly booked in this location.

**Issue #, if available:**
#154

**Description of changes:**
* IP blocks are booked in the location specified in the IonosCloudMachine spec
* Location is written into the Machine status

**Special notes for your reviewer:**

**Checklist:**
- [ ] Documentation updated
- [x] Unit Tests added
- [ ] E2E Tests added
- [x] Includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)

2024-07-11 14:51 UTC, lubedacht requested changes

2024-07-11 14:51 UTC, lubedacht commented on internal/ionoscloud/client.go
> +	GetDatacenterLocationByID(datacenterID string) (string, error)
Why not passing a context here?

2024-07-11 14:51 UTC, lubedacht commented on internal/ionoscloud/client/client.go
> +	datacenter, _, err := c.API.DataCentersApi.DatacentersFindById(context.Background(), datacenterID).Execute()
context.Background doesn't sound like a good idea

2024-07-12 09:40 UTC, lubedacht submitted a review, later dismissed

2024-07-12 10:01 UTC, piepmatz reviewed
What about using the location from the status if set instead of querying the Cloud API again?

2024-07-12 10:11 UTC, piepmatz commented on internal/service/cloud/ipblock_test.go
> +}
Right now this is mostly overhead: You use it only once and there the error was even checked before calling this method.
So rather just move the `s.Equal(exampleLocation, location)` check where this function is called.

2024-07-12 12:17 UTC, piepmatz approved these changes

2024-07-15 11:06 UTC, merged